version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`domain.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    depends_on:
      - auth-api
      - todos-api
      - users-api
    networks:
      - app-network

  auth-api:
    build: 
      context: ./auth-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api.rule=Host(`auth.domain.com`)"
      - "traefik.http.routers.auth-api.entrypoints=websecure"
      - "traefik.http.routers.auth-api.tls.certresolver=myresolver"
    networks:
      - app-network

  todos-api:
    build: 
      context: ./todos-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos-api.rule=Host(`todos.domain.com`)"
      - "traefik.http.routers.todos-api.entrypoints=websecure"
      - "traefik.http.routers.todos-api.tls.certresolver=myresolver"
    depends_on:
      - redis
    networks:
      - app-network

  users-api:
    build: 
      context: ./users-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-api.rule=Host(`users.domain.com`)"
      - "traefik.http.routers.users-api.entrypoints=websecure"
      - "traefik.http.routers.users-api.tls.certresolver=myresolver"
    networks:
      - app-network

  log-message-processor:
    build: 
      context: ./log-message-processor
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  letsencrypt:
